# Generated by Django 5.1.6 on 2025-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En Attente"),
                    ("VALIDEE", "Validee"),
                    ("REJETEE", "Rejetee"),
                ],
                default="EN_ATTENTE",
                max_length=10,
            ),
        ),
    ]
