# Generated by Django 5.1.6 on 2025-02-25 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0004_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('rejete', 'Rejeté'), ('accepte', 'Accepté')], default='en_attente', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
