# Generated by Django 5.1.6 on 2025-02-26 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0005_annonce_user_alter_annonce_statut_client_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("VALIDEE", "Validée"),
                    ("REJETEE", "Rejetée"),
                ],
                default="EN_ATTENTE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annonces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
