# Generated by Django 5.1.6 on 2025-02-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0007_favori"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="date_paiement",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
