# Generated by Django 5.1.6 on 2025-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0008_annonce_date_paiement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annonce",
            name="date_paiement",
        ),
        migrations.RemoveField(
            model_name="annonce",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="annonce",
            name="paiement_statut",
            field=models.CharField(
                choices=[("NON_PAYEE", "Non Payée"), ("PAYEE", "Payée")],
                default="NON_PAYEE",
                max_length=10,
            ),
        ),
    ]
