# Generated by Django 5.1.6 on 2025-02-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announces', '0011_remove_favori_date_annonce_date_favori_date_ajout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(default='8DC9A4C30F', max_length=20, unique=True)),
                ('banque', models.CharField(choices=[('Bankily', 'Bankily'), ('Masrivi', 'Masrivi'), ('Sedad', 'Sedad')], max_length=50)),
                ('numero_facture', models.CharField(max_length=50)),
                ('justificatif', models.ImageField(upload_to='paiements/')),
                ('date', models.DateTimeField(auto_now_add=True, help_text="Date et heure de soumission de l'annonce.")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='announces.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
