# Generated by Django 5.1.6 on 2025-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='numero_paiement',
            field=models.CharField(default='66A787E2A1', max_length=20, unique=True),
        ),
    ]
