# Generated by Django 5.1.6 on 2025-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0002_annonce_is_paid_alter_annonce_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
