# Generated by Django 5.1.6 on 2025-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0003_annonce_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
