# Generated by Django 5.1.6 on 2025-02-28 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0009_remove_annonce_date_paiement_remove_annonce_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favori',
            name='date_ajout',
        ),
        migrations.AddField(
            model_name='favori',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure de soumission de l'annonce."),
            preserve_default=False,
        ),
    ]
