# Generated by Django 5.1.6 on 2025-02-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0011_remove_favori_date_annonce_date_favori_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='announces.groupcategorie'),
            preserve_default=False,
        ),
    ]
