# Generated by Django 5.1.6 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_paiement_numero_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='numero_paiement',
            field=models.CharField(default='7DD1A97B8B', max_length=20, unique=True),
        ),
    ]
